project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: "Pablo Mas"
  favicon: favicon.png
  twitter-card: true
  site-url: https://pablo-mas.github.io/
  navbar:
    title: '‏ ‏ ‎ Pablo Mas'
    background: white
    foreground: black
    logo: favicon.gif

    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      # - research.qmd
      # - posts.qmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    mainfont: roboto
    css: styles.css
    toc: true
    linkcolor: rgb(51, 204, 204)
