project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: "Pablo Mas"
  favicon: favicon.png
  twitter-card: true
  site-url: https://pablo-mas.github.io/
  navbar:
    title: '‏ ‏ ‎ Pablo Mas'
    # logo: id-round.png

    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - research.qmd
      - posts.qmd
      
theme:
  light: flatly
  dark: darkly

format:
  html:
    theme: sandstone
    mainfont: roboto
    css: styles.css
    toc: true



