---
title: "Resume"
format:
  html:
    toc: true
    toc-title: "CV"
    number-sections: false
---

<div style="text-align: justify">*PhD candidate specialized in machine learning for drug discovery, with an emphasis on improving exploration and exploitation
during lead optimization. Conducting my research within the Theoretical Chemistry Group at ENS-PSL and the Integrated Drug
Discovery team at Sanofi. I am also pursuing an MBA at the Collège des Ingénieurs and teaching at ENS-PSL and Le Wagon bootcamp.*</div>  

<br>

## Education

#### **Doctor of Philosophy - PhD** <span style="float: right; font-size: medium;">10/2022 -- Present</span>
###### *École Normale Supérieure (ENS Ulm)*  <span style="float: right; font-size: medium;">Paris, France</span>
<div style="text-align: justify">Conducted research on machine learning applications in drug discovery and theoretical chemistry, in collaboration with Sanofi.
Under the supervision of Pr. Rodolphe Vuilleumier (ENS) and Dr. Marc Bianciotto (Sanofi).</div>  

#### **Master of Business Administration - MBA** <span style="float: right; font-size: medium;">01/2023 -- Present</span>
###### *Collège des Ingénieurs (CDI Paris)*  <span style="float: right; font-size: medium;">Paris, France</span>
<div style="text-align: justify">Selective MBA program designed for top graduates from leading French Engineering Schools.</div>  

#### **Master of Science - MSc** <span style="float: right; font-size: medium;">09/2021 -- 09/2022</span>
###### *BME Paris - PSL University*  <span style="float: right; font-size: medium;">Paris, France</span>
<div style="text-align: justify">Relevant courses: Deep learning and neurosciences - Deep learning and neurocomputational projects - Quantification for
Neuroimaging - Machine Learning for Bioimaging</div>  

#### **Master of Science ("Diplôme d’ingénieur") - MSc** <span style="float: right; font-size: medium;">09/2018 -- 09/2021</span>
###### *ESPCI Paris*  <span style="float: right; font-size: medium;">Paris, France</span>
<div style="text-align: justify">Biotechnology specialization (3rd year): Systems biology and neurobiology - Biochemistry and molecular biotechnology - Deep
learning - Statistical learning - Advanced analytical chemistry</div>  

#### **Bachelor of Science - BSc** <span style="float: right; font-size: medium;">09/2016 -- 09/2018</span>
###### *Sorbonne University*  <span style="float: right; font-size: medium;">Paris, France</span>
<div style="text-align: justify">Dual bachelor’s degree with majors in physics and chemistry.</div>  


## Experience

#### **Research scientist (CIFRE PhD)** <span style="float: right; font-size: medium;">10/2022 -- Present</span>
###### *Sanofi*  <span style="float: right; font-size: medium;">Paris, France</span>
<div style="text-align: justify; line-height: 1.5; margin-top: 0; margin-bottom: 0;">
- Developed rational exploration and exploitation strategies for molecule prioritization during the lead optimization phase,
supported by a comprehensive toolkit for medicinal chemists.
- Simulated active-learning based selection scenarios on legacy drug discovery projects.
- Developed QSAR/QSPR models in low and high data regimes.
</div>  

#### **Research intern** <span style="float: right; font-size: medium;">02/2022 -- 09/2022</span>
###### *Aramis LAB (INRIA & Paris Brain Institute)*  <span style="float: right; font-size: medium;">Paris, France</span>
<div style="text-align: justify; line-height: 1.5; margin-top: 0; margin-bottom: 0;">
- Developed deep learning algorithms using graph neural networks for automated segmentation of peptide accumulation in
whole-slide images, enabling improved stratification of Alzheimer’s disease patients.
</div>  

#### **Research intern** <span style="float: right; font-size: medium;">04/2021 -- 08/2021</span>
###### *LSABM (ESPCI Paris - PSL)*  <span style="float: right; font-size: medium;">Paris, France</span>
<div style="text-align: justify; line-height: 1.5; margin-top: 0; margin-bottom: 0;">
- Developed a LC-MS method to detect mustard gas-modified DNA traces in biological samples, in collaboration with the French
Defence Procurement Agency.
</div>

#### **Analytical scientist intern** <span style="float: right; font-size: medium;">07/2020 -- 12/2020</span>
###### *Adocia*  <span style="float: right; font-size: medium;">Lyon, France</span>
<div style="text-align: justify; line-height: 1.5; margin-top: 0; margin-bottom: 0;">
- Developed and characterized (via HPLC and NMR) a protective hydrogel for islets of Langerhans (beta cells) as part of a cell
therapy project aimed at creating an artificial pancreas.
</div>

#### **Research intern** <span style="float: right; font-size: medium;">06/2018 -- 08/2018</span>
###### *Phenix Lab (CNRS)*  <span style="float: right; font-size: medium;">Paris, France</span>
<div style="text-align: justify; line-height: 1.5; margin-top: 0; margin-bottom: 0;">
- Investigated water dynamics in 15th-century paintings through NMR relaxometry, X-ray, and IR spectroscopy.
</div>

#### **Data analyst intern** <span style="float: right; font-size: medium;">05/2017 -- 08/2017</span>
###### *Development Alternatives Incorporated*  <span style="float: right; font-size: medium;">Washington DC, USA</span>
<div style="text-align: justify; line-height: 1.5; margin-top: 0; margin-bottom: 0;">
- Developed data visualization dashboards and contributed to a report for the Aspen Institute : “A Global Opportunity: Get Youth
Working”.
</div>

## Skills
<div style="text-align: justify; line-height: 1.5; margin-top: 0; margin-bottom: 0;">
**Tools** <span style="float: right; font-size: medium;">Python (scikit-learn, PyTorch, Tensorflow, RDKit, deepchem...), Git, AWS, Matlab, SQL</span>

**Communication** <span style="float: right; font-size: medium;">French (native), English (fluent - C1 level), Spanish (intermediate - B1 level)</span>
</div>


## Extracurricular activities
<div style="text-align: justify; line-height: 1.5; margin-top: 0; margin-bottom: 0;">
- Treasurer of the ESPCI Paris – PSL student’s office, in charge of a 150 000€ budget.
- External Relations Officer of the ESPCI Paris – PSL sports union.
- **Sports**: Handball (15 years, two-time high-school champion of Morocco), Diving (PADI 2), Skiing, Squash.
</div> 